### PR TITLE
Update install_debian.yml

### PR DESCRIPTION
**Pull request by anon8675309**
fix: Install gpg before attempting to use it #12

### CODE REVIEW

**Comment by anon8675309** [comment]
Found an edge case where it would fail. If `apt update` had never been run, apt would say "no package matching 'gpg' is available".  Fixed by making sure the cache is updated before we attempt to install gpg.

**Review by darkwizard242 — COMMENTED** [review]
Thank you @anon8675309 for the PR.

Can you please change it to:
```yaml
- name: Update repository cache and install gnupg2
  ansible.builtin.apt:
    name: gnupg2
    update_cache: true
  when: "ansible_os_family == 'Debian'"

```

This is because we can handle updating repository cache in the same task as installing it. As for gnupg2, that is simply because it is a redesigned version of GnuPG.

**Comment by anon8675309** [comment]
Absolutely. Thank you for the feedback.

**Comment by darkwizard242** [comment]
Sorry @anon8675309  - finally got back to PR. I will merge and release a new version.

**Pull request merged**
